const posts = [
  {
    id: 'post-1',
    title: 'Best Weapons for Shenhe in Genshin Impact',
    href: '/posts/post-1',
    image: '/images/sample1.jpg',
    category: 'Genshin Impact',
    description: 'Find out the best weapon builds for Shenhe.',
    date: '2025-06-21T08:00:00Z', // 18분 전
  },
  {
    id: 'post-2',
    title: 'Shadowverse Beginner Tips',
    href: '/posts/post-2',
    image: '/images/sample2.jpg',
    category: 'Shadowverse',
    description: 'Learn how to get started in Shadowverse.',
    date: '2025-06-21T07:30:00Z', // 48분 전
  },
  {
    id: 'post-3',
    title: 'Dune Awakening Skorda Walkthrough',
    href: '/posts/post-3',
    image: '/images/sample3.jpg',
    category: 'Dune: Awakening',
    description: 'Track down Skorda in this intense Dune Awakening quest.',
    date: '2025-06-21T07:00:00Z', // 1시간 전
  },
  {
    id: 'post-4',
    title: 'Making a Martyr Quest Guide - Dune Awakening',
    href: '/posts/post-4',
    image: '/images/sample4.jpg',
    category: 'Dune: Awakening',
    description: 'Complete the Making a Martyr quest efficiently.',
    date: '2025-06-21T06:00:00Z',
  },
  {
    id: 'post-5',
    title: 'Where to Find Irradiated Slag in Dune Awakening',
    href: '/posts/post-5',
    image: '/images/sample5.jpg',
    category: 'Dune: Awakening',
    description: 'Find Irradiated Slag for late-game crafting.',
    date: '2025-06-21T05:00:00Z',
  },
  {
    id: 'post-6',
    title: 'Lies of P Trophy Guide',
    href: '/posts/post-6',
    image: '/images/sample6.jpg',
    category: 'Lies of P',
    description: 'Unlock every achievement in Lies of P.',
    date: '2025-06-21T05:00:00Z',
  },
  {
    id: 'post-7',
    title: 'The Valley Pirates Quest in Dreamlight Valley',
    href: '/posts/post-7',
    image: '/images/sample7.jpg',
    category: 'Dreamlight Valley',
    description: 'Final friendship quest guide for Peter Pan.',
    date: '2025-06-21T04:00:00Z',
  },
  {
    id: 'post-8',
    title: 'Act 2 Walkthrough - The Alters',
    href: '/posts/post-8',
    image: '/images/sample8.jpg',
    category: 'The Alters',
    description: 'Step-by-step guide to complete Act 2.',
    date: '2025-06-21T03:00:00Z',
  },
  {
    id: 'post-9',
    title: 'How to Farm Star Crystals in Wuthering Waves',
    href: '/posts/post-9',
    image: '/images/sample9.jpg',
    category: 'Wuthering Waves',
    description: 'Efficient routes and tips for farming Star Crystals.',
    date: '2025-06-21T02:00:00Z',
  },
  {
    id: 'post-10',
    title: 'Zelda: Tears of the Kingdom – Shrine Locations',
    href: '/posts/post-10',
    image: '/images/sample10.jpg',
    category: 'Zelda: TotK',
    description: 'All shrine locations and puzzle solutions.',
    date: '2025-06-21T01:00:00Z',
  },
  {
    id: 'post-11',
    title: 'Palworld Best Partner Combos',
    href: '/posts/post-11',
    image: '/images/sample11.jpg',
    category: 'Palworld',
    description: 'Optimize your Palworld team with synergy tips.',
    date: '2025-06-21T00:00:00Z',
  },
  {
    id: 'post-12',
    title: 'How to Beat The Butcher in Diablo IV',
    href: '/posts/post-12',
    image: '/images/sample12.jpg',
    category: 'Diablo IV',
    description: 'Tactics to defeat the infamous Butcher boss.',
    date: '2025-06-20T23:00:00Z',
  },
  {
    id: 'post-13',
    title: 'Tips for Winning in Marvel Snap',
    href: '/posts/post-13',
    image: '/images/sample13.jpg',
    category: 'Marvel Snap',
    description: 'Climb the ranks quickly in Marvel Snap with this guide.',
    date: '2025-06-20T22:00:00Z',
  },
    {
    id: 'post-14',
    title: 'Tips for Winning in Marvel Snap',
    href: '/posts/post-14',
    image: '/images/sample13.jpg',
    category: 'Marvel Snap',
    description: 'Climb the ranks quickly in Marvel Snap with this guide.',
    date: '2025-06-20T22:00:00Z',
  },
    {
    id: 'post-15',
    title: 'Tips for Winning in Marvel Snap',
    href: '/posts/post-15',
    image: '/images/sample13.jpg',
    category: 'Marvel Snap',
    description: 'Climb the ranks quickly in Marvel Snap with this guide.',
    date: '2025-06-20T22:00:00Z',
  },
]

export default posts